# Generated by Django 3.2.3 on 2021-05-20 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_caidat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caidat',
            old_name='admin',
            new_name='adminname',
        ),
    ]
