# Generated by Django 3.2.3 on 2021-05-20 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_admin_caidat_adminname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caidat',
            old_name='adminname',
            new_name='admin',
        ),
    ]
