# Generated by Django 3.2.3 on 2021-05-20 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_adminname_caidat_admin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CaiDat',
            new_name='Setting',
        ),
    ]
